### PR TITLE
Search result restoration

### LINKED ISSUE #759: Search Results List Not Restored On Orientation
* **App build number:**
0.13.0-SNAPSHOT

* **What did you expected to happen?** 
Rotating device when search results list shown would redisplay search results list

* **What happened instead?**
List was hidden

* **Steps to reproduce:**
Click search results list button and rotate device. Results will not be shown after orientation change.

### PR DESCRIPTION
**Pull request by sarahlensing**
- Updates how we handle restoring the options menu so that we don't try to call methods on it before it has been created
- Fixes bug which prevented options menu buttons from being restored on device rotation when viewing search results
- Fixes bug which didnt restore search results list view on device orientation
- Fixes bug which caused the settings button to show (upon back pressing to search results) when rotating the device while viewing the route preview, route preview directions, route, and route directions screens

Closes #759

### CODE REVIEW

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt [hunk 1]
```diff
@@ -156,7 +160,7 @@ open class MainPresenterImpl(val mapzenLocation: MapzenLocation, val bus: Bus,
   }
 
   private fun onRestoreViewStateSearchResults() {
-    mainViewController?.hideSettingsBtn()
+    // Do nothing.
```
Comment (msmollin) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: Why override if we're doing nothing?

Comment (msmollin) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: Per our discussion in slack, this is because we need the `when` statement to be exhaustive. Let's try out moving these into just anonymous blocks that get executed at the actual `when` statement rather than separate functions. Should make the code more concise and readable.

Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: Updated.
