### PR TITLE
Dont speak merge instruction on short ramp & add debug location receiver

### LINKED ISSUE #460: Remove verbal alert from 'Merge maneuver' when not sent from service
* **Device name:** samsung Model: SM-G900V
* **Android Version:** 5.0
* **App build number:** master-1228
* **What did you expected to happen?** That no verbal alert instruction will be given for 'Merge maneuvers' on short ramps (< 1.5 km)
* **What happened instead?** The service was updated on 3/7 to not send the 'Merge maneuver' verbal alert instruction on short ramps - however, the app is calling out: "In a 1/4 mile" with no distance
* **Steps to reproduce:** Any merge maneuver with prior short ramp

### PR DESCRIPTION
**Pull request by sarahlensing**
Closes #460

### CODE REVIEW

File: app/src/main/kotlin/com/mapzen/erasermap/receiver/MockLocationReceiver.kt [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import com.mapzen.erasermap.model.event.LocationChangeEvent
+import com.squareup.otto.Bus
+import javax.inject.Inject
+
+/**
+ * Receiver for debug purposes. Update mock location from the command line using
+ *
+ * adb shell am broadcast -a com.mapzen.erasermap.SET_MOCK_LOCATION --es lat "40.6681024" --es lng "-73.9808297"
+ */
+public class MockLocationReceiver : BroadcastReceiver() {
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/receiver/MockLocationReceiver.kt]: This is dope.
