### PR TITLE
location off messaging

### LINKED ISSUE #726: New User Messaging When Location Off
Device name: Galaxy S6 Edge
Android Version: 5.1.1 
App build number: dev 
What did you expected to happen? When searching for a location I would be able to click the navigation button and it would bring up directions. 
What happened instead? I clicked on the navigation and the navigation pane disappeared. 
Steps to reproduce: Turn location services off. Download the app. Open the app. Search for a location. Click the nav icon.
Attach a screenshot
Attach device logs

** it appears that this happens when the user has location tracking disabled - would be great to let the user know that they need location services turned on, but maybe give them a link to read more on what you all are tracking and how

If something happened while you were routing, share with us:

Where were you?
Routing from origin:
Routing to destination:

If something happened while you were searching, share with us:

Where were you?

### PR DESCRIPTION
**Pull request by sarahlensing**
- Upgrades app to Mapzen Android SDK 1.1.0
- Adds `LocationClientManager` to facilitate connecting `LostApiClient` and running queued tasks when it is connected
- Shows an `AlertDialog` when user tries to view route preview and location is disabled. Uses `SettingsApi` to launch system `Location` UI to update settings

TODO
- Remove bluetooth permission (https://github.com/mapzen/eraser-map/issues/730) when new version of Lost rolled out (https://github.com/mapzen/lost/issues/121)
- Add `SettingsApi` handling for location disabled in route preview & routing screens (https://github.com/mapzen/eraser-map/issues/728)

Closes #726

### CODE REVIEW

File: app/src/main/kotlin/com/mapzen/erasermap/model/LocationClientManager.kt [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package com.mapzen.erasermap.model
+
+import com.mapzen.android.lost.api.LostApiClient
+
+interface LocationClientManager {
+
+  abstract fun getClient(): LostApiClient?
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/model/LocationClientManager.kt]: `abstract` qualifier is implied for functions declared in an interface so not required here but no real harm in having it.

File: app/src/main/kotlin/com/mapzen/erasermap/model/LocationFactory.kt [hunk 2]
```diff
@@ -0,0 +1,12 @@
+package com.mapzen.erasermap.model
+
+import android.app.Application
+import com.mapzen.android.lost.api.LostApiClient
+import com.mapzen.android.lost.api.LostApiClient.ConnectionCallbacks
+
+/**
+ * Interface used by [LocationClientManager] implementations to create [LostApiClient]
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/model/LocationFactory.kt]: I did not know there was special syntax to link to a class in kdoc. Super cool.

File: app/src/test/kotlin/com/mapzen/erasermap/model/LostClientManagerTest.kt [hunk 3]
```diff
@@ -0,0 +1,86 @@
+package com.mapzen.erasermap.model
+
+import android.app.Application
+import com.mapzen.android.lost.api.LostApiClient
+import org.assertj.core.api.Assertions.assertThat
+import org.junit.Before
+import org.junit.Test
+import org.mockito.Mockito
+
+class LostClientManagerTest {
```
Comment (ecgreb) [inline app/src/test/kotlin/com/mapzen/erasermap/model/LostClientManagerTest.kt]: :+1:

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt [hunk 4]
```diff
@@ -2,12 +2,17 @@ package com.mapzen.erasermap.presenter
 
 import android.location.Location
 import android.util.Log
+import com.mapzen.android.lost.api.LocationServices
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: Unused imports

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt [hunk 5]
```diff
@@ -222,6 +229,25 @@ open class MainPresenterImpl(val mapzenLocation: MapzenLocation, val bus: Bus,
...
+      locationClientManager.connect()
+      locationClientManager.addRunnableToRunOnConnect(
+          Runnable { onRoutePreviewEvent(event) }
+      )
+      return
+    }
+
+    val locationStatusCode = locationSettingsChecker.getLocationStatusCode(mapzenLocation,
+        locationClientManager)
+    when (locationStatusCode) {
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: Maybe better to use an `if` statement here? `when` in Kotlin is kinda like `switch` in Java. This works but feels a little weird to only have one case.

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt [hunk 6]
```diff
@@ -466,6 +516,14 @@ open class MainPresenterImpl(val mapzenLocation: MapzenLocation, val bus: Bus,
   }
 
   override fun configureMapzenMap() {
+    if (locationClientManager.getClient() == null) {
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: `updateLocation()`, `onClickStartNavigation()`, `generateRoutePreview()`, and `configureMapzenMap()` all use similar logic to check if the client is connected and if not post a `Runnable`. It could be cool to add a private method that takes the function to be run as a parameter.

```kotlin
  private fun connectAndPostRunnable(run: () -> Unit) {
    locationClientManager.connect()
    locationClientManager.addRunnableToRunOnConnect(Runnable { run })
  }
```

Then this logic would become:

```kotlin
    if (locationClientManager.getClient() == null) {
      connectAndPostRunnable { generateRoutePreview() }
      return
    }
```

File: app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt [hunk 7]
```diff
@@ -1,5 +1,6 @@
 package com.mapzen.erasermap.controller
 
+import android.content.DialogInterface
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt]: Unused import

File: app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt [hunk 8]
```diff
@@ -35,6 +40,7 @@ import org.junit.Before
 import org.junit.Test
 import org.mockito.Mockito
 import org.mockito.Mockito.`when`
+import org.mockito.Mockito.any
```
Comment (ecgreb) [inline app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt]: Unused import

File: app/src/main/kotlin/com/mapzen/erasermap/model/LocationClientManager.kt (hunk 1 above)
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/model/LocationClientManager.kt]: Rm'd

File: app/build.gradle [hunk 9]
```diff
@@ -130,7 +130,7 @@ dependencies {
   compile 'com.android.support:appcompat-v7:23.4.0'
   compile 'com.android.support:support-v4:23.4.0'
   compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
-  compile 'com.mapzen:mapzen-android-sdk:1.0.10-SNAPSHOT'
+  compile 'com.mapzen:mapzen-android-sdk:1.1.0'
```
Comment (sarahlensing) [inline app/build.gradle]: I'm not seeing that but I think I remember this happening before for you. I'll circle back to this issue after addressing the others.

File: app/src/main/kotlin/com/mapzen/erasermap/model/LostClientManager.kt [hunk 10]
```diff
@@ -0,0 +1,56 @@
...
+import android.app.Application
+import com.mapzen.android.lost.api.LostApiClient
+import java.util.ArrayList
+
+/**
+ * Manages [LostApiClient] and its [ConnectionCallback] flow
+ */
+class LostClientManager(val application: Application, locationFactory: LocationFactory): LocationClientManager {
+
+  private var connecting = false
```
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/model/LostClientManager.kt]: Definitely would be. Updated to use an enum.

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt (hunk 6 above)
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: 👍 
Refactored.

File: app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt (hunk 7 above)
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt]: Rm'd

File: app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt (hunk 8 above)
Comment (sarahlensing) [inline app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt]: Rm'd

File: app/build.gradle (hunk 9 above)
Comment (ecgreb) [inline app/build.gradle]: Yeah I think so also. Probably not related to these changes so we can deal with it later if it persists.
