### PR TITLE
Peter/route preview

### LINKED ISSUE #135: Missing route_start and route_end map pins
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** When planning my route from X to Y, I expected to see map pins showing the `route_start` (from X) and `route_end` (to Y) locations.
* **What happened instead?** I only saw the routeline (`route`) and the current location gem (`find_me`). 
* **Steps to reproduce:** Plan a route to somewhere.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** AutoSmog & Oil Changers, San Francisco off Cesar Chavez St.
* **Routing from origin:** AutoSmog & Oil Changers, San Francisco off Cesar Chavez St.
* **Routing to destination:** 273 29th St (San Francisco, California, USA)

### LINKED ISSUE #172: Route selection map preview should show entire route
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** reproduces on master-518 (originally observed on master-481)
* **What did you expected to happen?** I should see a map of the entire route.
* **What happened instead?** I only see the portion immediately around the destination (the map doesn't refresh to center the entire route line in view once I route to my search result).
* **Steps to reproduce:** Simulate location to Eureka, CA. Search for McKinleyville, Humboldt County, California. Route to the search result. 
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were routing, share with us:

* **Where were you?** Eureka, CA (Target!)
* **Where were going to?** McKinleyville, California
* **Where were leaving from?** Eureka, CA (Target!)

### PR DESCRIPTION
**Pull request by kingofirony**
- Zooms out to an appropriate level to display route in route preview. 
- Adds begin and end pins.

Closes #135 
Closes #172

### CODE REVIEW

File: app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt [hunk 1]
```diff
@@ -571,6 +575,48 @@ public class MainActivity : AppCompatActivity(), MainViewController, RouteCallba
...
+        var lon: Double = (finish?.longitude + start?.longitude) / 2.0
+        mapController?.setMapPosition(lon, lat)
+
+        var numPixelsRequired = distance?.toFloat() / width.toFloat()
+        var zoomLevel = Math.log(((equatorCircumfrence * Math.abs(Math.cos(lat)))
+                / (numPixelsRequired?.toDouble()))) / Math.log(2.0)
+
+        setMapRotation(0f)
+        setMapTilt(0.0f)
+        mapController?.setMapZoom(zoomLevel.toFloat() * .8f)
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt]: Currently the map seems a little too zoomed out in route preview on my device (Nexus 5). Can we try `0.9f` scale factor here?

File: app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt [hunk 2]
```diff
@@ -571,6 +575,48 @@ public class MainActivity : AppCompatActivity(), MainViewController, RouteCallba
         hideProgress()
     }
 
+    private fun zoomToShowRoute(route: Route) {
+        //Get size of display For calculations
+        var mdisp = getWindowManager().getDefaultDisplay()
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt]: Prever `val` over `var` if value does not change.

File: app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt [hunk 3]
```diff
@@ -571,6 +575,48 @@ public class MainActivity : AppCompatActivity(), MainViewController, RouteCallba
...
+        var mdispSize = Point()
+        mdisp.getSize(mdispSize)
+        var width = mdispSize.y
+
+        var geometry = route?.getGeometry()
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt]: Most `?.` access in this method can be replaced with `.` since values are not nullable.

File: app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt [hunk 4]
```diff
@@ -248,6 +257,17 @@ public class MainActivityTest {
     }
 
     @Test
+    public fun showRoutePreview_shouldAddStartandEndPins() {
+        activity.showRoutePreview(getTestLocation(), getTestFeature())
+        activity.success(TestRoute())
+        Robolectric.flushForegroundThreadScheduler()
+        val shadowStartPin = ShadowExtractor.extract(activity.startPin) as ShadowMapData
+        val shadowEndPin = ShadowExtractor.extract(activity.startPin) as ShadowMapData
+        assertThat(shadowEndPin.points).isNotNull()
```
Comment (ecgreb) [inline app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt]: Let's add an assertion here to verify the start and end pins are actually added to `ShadowTangram.dataSources` as well.

For bonus points we could also verify the lat and long values of the pins match the test location and test feature :)

**Comment by ecgreb** [comment]
Edited description to add magic words to link to corresponding issues.
