### PR TITLE
Fix mock location

### LINKED ISSUE #584: Unable to set mock location
The "find me" button no longer recognizes mock locations set in the debug menu since migrating to the Mapzen SDK. Same issue with mock route gpx replay.

### PR DESCRIPTION
**Pull request by sarahlensing**
- Because the sdk's `LostApiClient is disconnected when starting navigation/pausing the main activity we need to re-enable mock mode when `mapzenMap?.isMyLocationEnabled = true` because a new `FusedLocationProviderImpl` is created (and by default has a `FusionEngine`, not a `MockEngine`)
- When starting navigation, we need to set the trace file after the location client has been connected and before we request location updates
- We need to set the mock location in the `MockLocationReceiver` so that the sdk will handle updating the current location tracker properly

Depends on https://github.com/mapzen/LOST/pull/54/files

Closes #584

### CODE REVIEW

File: app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt [hunk 1]
```diff
@@ -38,11 +36,11 @@ public class MapzenLocationImpl(val locationClient: LostApiClient,
...
-
-            if (settings.isMockLocationEnabled) {
-                LocationServices.FusedLocationApi?.setMockMode(true)
-                LocationServices.FusedLocationApi?.setMockLocation(settings.mockLocation)
-            }
+        }
+        if (settings.isMockLocationEnabled) {
+            LocationServices.FusedLocationApi?.setMockMode(true)
+            LocationServices.FusedLocationApi?.setMockLocation(settings.mockLocation)
+            LocationServices.FusedLocationApi?.setMockTrace(settings.mockRoute)
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt]: There is a separate checkbox preference for mock routing. We should check `settings.isMockRouteEnabled` before setting the trace file.

Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt]: Nice catch. I've pushed changes to check this setting. I also updated the way our settings behave so that enabling mock routing enables mock location as well.

File: app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt [hunk 2]
```diff
@@ -1,6 +1,8 @@
 package com.mapzen.erasermap.view
 
+import android.content.SharedPreferences
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt]: Unused import

File: app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt [hunk 3]
```diff
@@ -118,6 +134,24 @@ public class SettingsFragment : PreferenceFragment(), Preference.OnPreferenceCha
         getSettingsActivity().clearHistory(title)
     }
 
+    private fun updateMockTracePref(mockLocationEnabled: Boolean) {
+        if (!mockLocationEnabled) {
+            val prefs = PreferenceManager.getDefaultSharedPreferences(this.context)
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt]: `Fragment.getContext()` requires API 23. This will crash on older versions of Android

https://developer.android.com/reference/android/app/Fragment.html#getContext()

File: app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt [hunk 4]
```diff
@@ -118,6 +134,24 @@ public class SettingsFragment : PreferenceFragment(), Preference.OnPreferenceCha
...
+            prefs.edit().putBoolean(AndroidAppSettings.KEY_MOCK_ROUTE_ENABLED, false).commit()
+            val pref = findPreference(AndroidAppSettings.KEY_MOCK_ROUTE_ENABLED) as CheckBoxPreference
+            pref.isChecked = false
+        }
+    }
+
+    private fun updateMockLocationPref(mockTraceEnabled: Boolean) {
+        if (mockTraceEnabled) {
+            val prefs = PreferenceManager.getDefaultSharedPreferences(this.context)
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt]: Fragment.getContext() requires API 23. This will crash on older versions of Android

https://developer.android.com/reference/android/app/Fragment.html#getContext()

File: app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt (hunk 2 above)
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt]: Rm'd

File: app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt (hunk 3 above)
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt]: Updated to access context through activity.

File: app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt (hunk 4 above)
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt]: Updated to access context through activity.

**Comment by ecgreb** [comment]
So glad to have this feature back!
