### PR TITLE
Single tap consistency

### LINKED ISSUE #775: Single tap produces inconsistent map marker placement.
* **Device name:** 
Nexus 5
* **Android Version:** 
4.4.4
* **App build number:**
master-1811
* **What did you expected to happen?** 
That when I tapped on a map POI that the pin would land in the same spot every time, and that it would stick to the POI
* **What happened instead?**
The map pin lands all over the place, sometimes on the adjoining street, and then it doesn't seem to be attached to the POI but it doesn't jump either like previous issues.
* **Steps to reproduce:**
Find a POI listed on the map (school, business, etc.) and tap a few times close to it.
* **Attach a screenshot**
How about a video?
https://youtu.be/F2P7xUHoNx8

### PR DESCRIPTION
**Pull request by sarahlensing**
### Overview
Migrates from `FeaturePickListener` to `LabelPickListener`.

### Proposed Changes
The `LabelPickListener` ensures that coordinates returned are in the center of a label and is better suited for EM's needs.

Closes #775

### CODE REVIEW

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt [hunk 1]
```diff
@@ -9,6 +9,7 @@ import com.mapzen.pelias.gson.Result
 import com.mapzen.tangram.LngLat
 import com.mapzen.valhalla.Route
 import com.mapzen.valhalla.RouteCallback
+import java.util.HashMap
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt]: Unused import

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt [hunk 2]
```diff
@@ -272,7 +273,11 @@ open class MainPresenterImpl(val mapzenLocation: MapzenLocation, val bus: Bus,
     mainViewController?.layoutFindMeAboveSearchResults(features)
 
     val lngLat: LngLat?
-    if (poiTapPoint != null) {
+    if (poiCoordinates != null) {
+      lngLat = poiCoordinates
+      overridePlaceFeature(features[0])
+    }
+    else if (poiTapPoint != null) {
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: `else` on same line as closing brace?

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt [hunk 3]
```diff
@@ -290,9 +295,15 @@ open class MainPresenterImpl(val mapzenLocation: MapzenLocation, val bus: Bus,
...
-      val coordinates = ArrayList<Double>()
+    val geometry = Geometry()
+    val coordinates = ArrayList<Double>()
+    if (poiCoordinates != null) {
+      coordinates.add(poiCoordinates?.longitude as Double)
+      coordinates.add(poiCoordinates?.latitude as Double)
+      geometry.coordinates = coordinates
+      feature.geometry = geometry
+    }
+    else if (poiTapPoint != null) {
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: `else` on same line as closing brace?

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt [hunk 4]
```diff
@@ -842,18 +854,23 @@ open class MainPresenterImpl(val mapzenLocation: MapzenLocation, val bus: Bus,
     return rawFeature
   }
 
-  override fun onFeaturePicked(properties: Map<String, String>, x: Float, y: Float) {
+  override fun onFeaturePicked(properties: Map<String, String>?, coordinates: LngLat?, x: Float,
```
Comment (ecgreb) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: Change `coordinates` to `coords` to be consistent with parameter name in `MainPresenter` interface?

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt (hunk 1 above)
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt]: Rm'd

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt (hunk 2 above)
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: Fixed.

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt (hunk 3 above)
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: Fixed.

File: app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt (hunk 4 above)
Comment (sarahlensing) [inline app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt]: Fixed.
